// Releases data - embedded directly in JavaScript
const RELEASES_DATA = {
  "releases": [
    {
      "id": "1",
      "title": "시작",
      "titleEn": "Start Over",
      "artist": "Gaho",
      "releaseDate": "2020-02-01",
      "type": "single",
      "albumName": "이태원 클라쓰 OST Part 2",
      "albumNameEn": "Itaewon Class OST Part 2",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": true,
      "popularity": 1,
      "trackCount": 1
    },
    {
      "id": "2",
      "title": "Running",
      "titleEn": "Running",
      "artist": "Gaho",
      "releaseDate": "2020-10-30",
      "type": "single",
      "albumName": "스타트업 OST Part 5",
      "albumNameEn": "스타트업 OST Part 5",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": true,
      "popularity": 2,
      "trackCount": 1
    },
    {
      "id": "3",
      "title": "Yellow Light",
      "titleEn": "Yellow Light",
      "artist": "Gaho",
      "releaseDate": "2023-06-18",
      "type": "single",
      "albumName": "Yellow Light",
      "albumNameEn": "Yellow Light",
      "trackCount": 1,
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": true,
      "popularity": 3
    },
    {
      "id": "4",
      "title": "있어줘 Stay Here",
      "titleEn": "Stay Here",
      "artist": "Gaho",
      "releaseDate": "2018-05-03",
      "type": "single",
      "albumName": null,
      "albumNameEn": null,
      "coverImage": "images/releases/album-cover_stay-here.jpeg",
      "featured": true,
      "popularity": 4,
      "trackCount": 1
    },
    {
      "id": "5",
      "title": "Go On",
      "titleEn": "Go On",
      "artist": "Gaho",
      "releaseDate": "2025.05.25",
      "type": "single",
      "coverImage": "images/releases/album-cover_go-on.jpeg",
      "featured": true,
      "popularity": 5,
      "albumName": "불꽃야구 OST Part.2",
      "albumNameEn": "불꽃야구 OST Part.2",
      "trackCount": 1
    },
    {
      "id": "6",
      "title": "바람",
      "titleEn": "바람",
      "artist": "Gaho",
      "releaseDate": "2020.10.03",
      "type": "single",
      "coverImage": "images/releases/album-cover_stranger-2.jpeg",
      "featured": true,
      "popularity": 6,
      "albumName": "비밀의 숲 2 OST",
      "albumNameEn": "Stranger Things 2 OST",
      "trackCount": 1
    },
    {
      "id": "7",
      "title": "Right Now",
      "titleEn": "Right Now",
      "artist": "Gaho",
      "releaseDate": "2021-11-23",
      "type": "album",
      "coverImage": "images/releases/album-cover_fireworks.jpeg",
      "featured": true,
      "popularity": 7,
      "albumName": "Fireworks",
      "albumNameEn": "Fireworks",
      "trackCount": 12
    },
    {
      "id": "8",
      "title": "끝이 아니길",
      "titleEn": "끝이 아니길",
      "artist": "Gaho",
      "releaseDate": "2021-02-09",
      "type": "single",
      "coverImage": "images/releases/album-cover_not-the-end.jpeg",
      "featured": true,
      "popularity": 8,
      "albumName": "황후의 품격 OST",
      "albumNameEn": "황후의 품격 OST",
      "trackCount": 1
    },
    {
      "id": "9",
      "title": "시간",
      "titleEn": "시간",
      "artist": "Gaho",
      "releaseDate": "2021-06-23",
      "type": "single",
      "coverImage": "images/releases/album-cover_time-ost.jpeg",
      "featured": true,
      "popularity": 9,
      "albumName": "시간 OST",
      "albumNameEn": "시간 OST",
      "trackCount": 1
    },
    {
      "id": "10",
      "title": "그렇게 가슴은 뛴다",
      "titleEn": "그렇게 가슴은 뛴다",
      "artist": "Gaho",
      "releaseDate": "2020-01-22",
      "type": "single",
      "coverImage": "images/releases/album-cover_my-heart-is-beating.jpeg",
      "featured": true,
      "popularity": 10,
      "albumName": "내 뒤에 테리우스 OST",
      "albumNameEn": "내 뒤에 테리우스 OST",
      "trackCount": 1
    },
    {
      "id": "11",
      "title": "Rush Hour",
      "titleEn": "Rush Hour",
      "artist": "Gaho",
      "releaseDate": "2021-05-24",
      "type": "single",
      "coverImage": "images/releases/album-cover_rush-hour.jpeg",
      "featured": true,
      "popularity": 11,
      "albumName": "Rush Hour",
      "albumNameEn": "Rush Hour",
      "trackCount": 1
    },
    {
      "id": "12",
      "title": "남자를 몰라",
      "titleEn": "남자를 몰라",
      "artist": "Gaho",
      "releaseDate": "2020-10-27",
      "type": "single",
      "coverImage": "images/releases/album-cover_dont-know-you.jpeg",
      "featured": true,
      "popularity": 12,
      "albumName": "남자를 몰라 (삼성전자 뉴레트로 시리즈)",
      "albumNameEn": "남자를 몰라 (삼성전자 뉴레트로 시리즈)",
      "trackCount": 1
    },
    {
      "id": "13",
      "title": "RIDE",
      "titleEn": "RIDE",
      "artist": "Gaho",
      "releaseDate": "2021-11-23",
      "type": "album",
      "coverImage": "images/releases/album-cover_fireworks.jpeg",
      "featured": true,
      "popularity": 13,
      "albumName": "Fireworks",
      "albumNameEn": "Fireworks",
      "trackCount": 12
    },
    {
      "id": "14",
      "title": "Officially Missing You",
      "titleEn": "Officially Missing You",
      "artist": "Gaho",
      "releaseDate": "2021-07-15",
      "type": "single",
      "coverImage": "images/releases/album-cover_cyworld-bgm-2021.jpeg",
      "featured": true,
      "popularity": 14,
      "albumName": "싸이월드 BGM 2021",
      "albumNameEn": "싸이월드 BGM 2021",
      "trackCount": 1
    },
    {
      "id": "15",
      "title": "안개 속 어디로",
      "titleEn": "안개 속 어디로",
      "artist": "Gaho",
      "releaseDate": "2022-07-23",
      "type": "single",
      "coverImage": "images/releases/album-cover_where-to-in-the-fog.jpeg",
      "featured": true,
      "popularity": 15,
      "albumName": "왜 오수재인가 OST",
      "albumNameEn": "왜 오수재인가 OST",
      "trackCount": 1
    },
    {
      "id": "16",
      "title": "Only You",
      "titleEn": "Only You",
      "artist": "Gaho",
      "releaseDate": "2023-03-20",
      "type": "album",
      "coverImage": "images/releases/album-cover_diamond.jpeg",
      "featured": true,
      "popularity": 16,
      "albumName": "Diamond",
      "albumNameEn": "Diamond",
      "trackCount": 6
    },
    {
      "id": "17",
      "title": "Beautiful Night",
      "titleEn": "Beautiful Night",
      "artist": "Gaho",
      "releaseDate": "2023-03-20",
      "type": "album",
      "coverImage": "images/releases/album-cover_diamond.jpeg",
      "featured": true,
      "popularity": 17,
      "albumName": "Diamond",
      "albumNameEn": "Diamond",
      "trackCount": 6
    },
    {
      "id": "18",
      "title": "떠날 준비",
      "titleEn": "떠날 준비",
      "artist": "Gaho",
      "releaseDate": "2018-12-11",
      "type": "album",
      "coverImage": "images/releases/album-cover_preparation-for-a-journey.jpeg",
      "featured": true,
      "popularity": 18,
      "albumName": "Preparation For a Journey",
      "albumNameEn": "Preparation For a Journey",
      "trackCount": 5
    },
    {
      "id": "19",
      "title": "Going on",
      "titleEn": "Going on",
      "artist": "Gaho",
      "releaseDate": "2018-12-11",
      "type": "album",
      "coverImage": "images/releases/album-cover_preparation-for-a-journey.jpeg",
      "featured": true,
      "popularity": 19,
      "albumName": "Preparation For a Journey",
      "albumNameEn": "Preparation For a Journey",
      "trackCount": 5
    },
    {
      "id": "21",
      "title": "Lonely",
      "titleEn": "Lonely",
      "artist": "Gaho",
      "releaseDate": "2023-03-20",
      "type": "album",
      "coverImage": "images/releases/album-cover_diamond.jpeg",
      "featured": true,
      "popularity": 21,
      "albumName": "Diamond",
      "albumNameEn": "Diamond",
      "trackCount": 6
    },
    {
      "id": "22",
      "title": "Lost my way",
      "titleEn": "Lost my way",
      "artist": "Gaho",
      "releaseDate": "2021-11-23",
      "type": "album",
      "coverImage": "images/releases/album-cover_fireworks.jpeg",
      "featured": true,
      "popularity": 22,
      "albumName": "Fireworks",
      "albumNameEn": "Fireworks",
      "trackCount": 12
    },
    {
      "id": "23",
      "title": "마음대로",
      "titleEn": "마음대로",
      "artist": "Gaho",
      "releaseDate": "2021-11-23",
      "type": "album",
      "coverImage": "images/releases/album-cover_fireworks.jpeg",
      "featured": true,
      "popularity": 23,
      "albumName": "Fireworks",
      "albumNameEn": "Fireworks",
      "trackCount": 12
    },
    {
      "id": "24",
      "title": "Heaven",
      "titleEn": "Heaven",
      "artist": "Gaho",
      "releaseDate": "2018-12-11",
      "type": "album",
      "coverImage": "images/releases/album-cover_preparation-for-a-journey.jpeg",
      "featured": true,
      "popularity": 24,
      "albumName": "Preparation For a Journey",
      "albumNameEn": "Preparation For a Journey",
      "trackCount": 5
    }
  ]
};
