// Releases data - embedded directly in JavaScript
const RELEASES_DATA = {
  "releases": [
    {
      "id": "1",
      "title": "시작",
      "titleEn": "Start",
      "artist": "Gaho",
      "releaseDate": "2020-02-01",
      "type": "album",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": true,
      "popularity": 95
    },
    {
      "id": "2",
      "title": "Running",
      "titleEn": "Running",
      "artist": "Gaho",
      "releaseDate": "2020-10-30",
      "type": "album",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": true,
      "popularity": 92
    },
    {
      "id": "3",
      "title": "Yellow Light",
      "titleEn": "Yellow Light",
      "artist": "Gaho",
      "releaseDate": "2023-06-18",
      "type": "album",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": true,
      "popularity": 88
    },
    {
      "id": "4",
      "title": "있어줘 Stay Here",
      "titleEn": "Stay Here",
      "artist": "Gaho",
      "releaseDate": "2018-05-03",
      "type": "single",
      "coverImage": "images/releases/album-cover_stay-here.jpeg",
      "featured": true,
      "popularity": 97
    },
    {
      "id": "5",
      "title": "시작",
      "titleEn": "Start",
      "artist": "Gaho",
      "releaseDate": "2019-11-24",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": true,
      "popularity": 94
    },
    {
      "id": "6",
      "title": "Fly",
      "titleEn": "Fly",
      "artist": "Gaho",
      "releaseDate": "2019-03-27",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": true,
      "popularity": 89
    },
    {
      "id": "7",
      "title": "Pink Walk",
      "titleEn": "Pink Walk",
      "artist": "Gaho",
      "releaseDate": "2020-07-15",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": true,
      "popularity": 86
    },
    {
      "id": "8",
      "title": "Rush Hour",
      "titleEn": "Rush Hour",
      "artist": "Gaho",
      "releaseDate": "2021-02-09",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": true,
      "popularity": 91
    },
    {
      "id": "9",
      "title": "Right Now",
      "titleEn": "Right Now",
      "artist": "Gaho",
      "releaseDate": "2021-06-23",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": true,
      "popularity": 85
    },
    {
      "id": "10",
      "title": "Preparation",
      "titleEn": "Preparation",
      "artist": "Gaho",
      "releaseDate": "2020-01-22",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": true,
      "popularity": 82
    },
    {
      "id": "11",
      "title": "Ride",
      "titleEn": "Ride",
      "artist": "Gaho",
      "releaseDate": "2019-08-14",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": true,
      "popularity": 80
    },
    {
      "id": "12",
      "title": "Then",
      "titleEn": "Then",
      "artist": "Gaho",
      "releaseDate": "2019-05-30",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": true,
      "popularity": 78
    },
    {
      "id": "13",
      "title": "Beautiful",
      "titleEn": "Beautiful",
      "artist": "Gaho",
      "releaseDate": "2022-03-15",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 84
    },
    {
      "id": "14",
      "title": "Memories",
      "titleEn": "Memories",
      "artist": "Gaho",
      "releaseDate": "2021-11-10",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": true,
      "popularity": 81
    },
    {
      "id": "15",
      "title": "Starlight",
      "titleEn": "Starlight",
      "artist": "Gaho",
      "releaseDate": "2023-01-28",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 87
    },
    {
      "id": "16",
      "title": "Moonlight",
      "titleEn": "Moonlight",
      "artist": "Gaho",
      "releaseDate": "2022-09-05",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": true,
      "popularity": 79
    },
    {
      "id": "17",
      "title": "Daybreak",
      "titleEn": "Daybreak",
      "artist": "Gaho",
      "releaseDate": "2021-12-22",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": true,
      "popularity": 76
    },
    {
      "id": "18",
      "title": "Midnight",
      "titleEn": "Midnight",
      "artist": "Gaho",
      "releaseDate": "2020-05-18",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 83
    },
    {
      "id": "19",
      "title": "Sunrise",
      "titleEn": "Sunrise",
      "artist": "Gaho",
      "releaseDate": "2019-07-09",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": true,
      "popularity": 77
    },
    {
      "id": "20",
      "title": "Sunset",
      "titleEn": "Sunset",
      "artist": "Gaho",
      "releaseDate": "2022-04-20",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": true,
      "popularity": 74
    },
    {
      "id": "21",
      "title": "Dreams",
      "titleEn": "Dreams",
      "artist": "Gaho",
      "releaseDate": "2021-08-13",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": true,
      "popularity": 72
    },
    {
      "id": "22",
      "title": "Hope",
      "titleEn": "Hope",
      "artist": "Gaho",
      "releaseDate": "2020-11-25",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": true,
      "popularity": 75
    },
    {
      "id": "23",
      "title": "Wish",
      "titleEn": "Wish",
      "artist": "Gaho",
      "releaseDate": "2019-12-18",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": true,
      "popularity": 73
    },
    {
      "id": "24",
      "title": "Promise",
      "titleEn": "Promise",
      "artist": "Gaho",
      "releaseDate": "2023-03-07",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": true,
      "popularity": 88
    },
    {
      "id": "25",
      "title": "Forever",
      "titleEn": "Forever",
      "artist": "Gaho",
      "releaseDate": "2022-07-14",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": true,
      "popularity": 71
    },
    {
      "id": "26",
      "title": "Always",
      "titleEn": "Always",
      "artist": "Gaho",
      "releaseDate": "2021-05-19",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": true,
      "popularity": 70
    },
    {
      "id": "27",
      "title": "Together",
      "titleEn": "Together",
      "artist": "Gaho",
      "releaseDate": "2020-09-03",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": true,
      "popularity": 69
    },
    {
      "id": "28",
      "title": "Alone",
      "titleEn": "Alone",
      "artist": "Gaho",
      "releaseDate": "2019-10-11",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": true,
      "popularity": 68
    },
    {
      "id": "29",
      "title": "Freedom",
      "titleEn": "Freedom",
      "artist": "Gaho",
      "releaseDate": "2023-05-02",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 86
    },
    {
      "id": "30",
      "title": "Journey",
      "titleEn": "Journey",
      "artist": "Gaho",
      "releaseDate": "2022-10-26",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 67
    },
    {
      "id": "31",
      "title": "Destiny",
      "titleEn": "Destiny",
      "artist": "Gaho",
      "releaseDate": "2021-09-17",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 66
    },
    {
      "id": "32",
      "title": "Miracle",
      "titleEn": "Miracle",
      "artist": "Gaho",
      "releaseDate": "2020-12-08",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 65
    },
    {
      "id": "33",
      "title": "Believe",
      "titleEn": "Believe",
      "artist": "Gaho",
      "releaseDate": "2019-04-23",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 64
    },
    {
      "id": "34",
      "title": "Victory",
      "titleEn": "Victory",
      "artist": "Gaho",
      "releaseDate": "2023-02-14",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 85
    },
    {
      "id": "35",
      "title": "Celebrate",
      "titleEn": "Celebrate",
      "artist": "Gaho",
      "releaseDate": "2022-08-31",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 63
    },
    {
      "id": "36",
      "title": "Thunder",
      "titleEn": "Thunder",
      "artist": "Gaho",
      "releaseDate": "2021-07-06",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 62
    },
    {
      "id": "37",
      "title": "Lightning",
      "titleEn": "Lightning",
      "artist": "Gaho",
      "releaseDate": "2020-06-12",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 61
    },
    {
      "id": "38",
      "title": "Storm",
      "titleEn": "Storm",
      "artist": "Gaho",
      "releaseDate": "2019-09-28",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 60
    },
    {
      "id": "39",
      "title": "Rainbow",
      "titleEn": "Rainbow",
      "artist": "Gaho",
      "releaseDate": "2023-04-19",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 84
    },
    {
      "id": "40",
      "title": "Echo",
      "titleEn": "Echo",
      "artist": "Gaho",
      "releaseDate": "2022-11-11",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 59
    },
    {
      "id": "41",
      "title": "Whisper",
      "titleEn": "Whisper",
      "artist": "Gaho",
      "releaseDate": "2021-10-04",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 58
    },
    {
      "id": "42",
      "title": "Shout",
      "titleEn": "Shout",
      "artist": "Gaho",
      "releaseDate": "2020-08-27",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 57
    },
    {
      "id": "43",
      "title": "Voice",
      "titleEn": "Voice",
      "artist": "Gaho",
      "releaseDate": "2019-11-15",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 56
    },
    {
      "id": "44",
      "title": "Melody",
      "titleEn": "Melody",
      "artist": "Gaho",
      "releaseDate": "2023-07-08",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 90
    },
    {
      "id": "45",
      "title": "Harmony",
      "titleEn": "Harmony",
      "artist": "Gaho",
      "releaseDate": "2022-12-25",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 55
    },
    {
      "id": "46",
      "title": "Rhythm",
      "titleEn": "Rhythm",
      "artist": "Gaho",
      "releaseDate": "2021-04-16",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 54
    },
    {
      "id": "47",
      "title": "Beat",
      "titleEn": "Beat",
      "artist": "Gaho",
      "releaseDate": "2020-03-11",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 53
    },
    {
      "id": "48",
      "title": "Song",
      "titleEn": "Song",
      "artist": "Gaho",
      "releaseDate": "2019-06-20",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 52
    },
    {
      "id": "49",
      "title": "Dance",
      "titleEn": "Dance",
      "artist": "Gaho",
      "releaseDate": "2023-08-22",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 89
    },
    {
      "id": "50",
      "title": "Move",
      "titleEn": "Move",
      "artist": "Gaho",
      "releaseDate": "2022-05-13",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 51
    },
    {
      "id": "51",
      "title": "Flow",
      "titleEn": "Flow",
      "artist": "Gaho",
      "releaseDate": "2021-01-29",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 50
    },
    {
      "id": "52",
      "title": "Groove",
      "titleEn": "Groove",
      "artist": "Gaho",
      "releaseDate": "2020-04-07",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 49
    },
    {
      "id": "53",
      "title": "Swing",
      "titleEn": "Swing",
      "artist": "Gaho",
      "releaseDate": "2019-08-02",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 48
    },
    {
      "id": "54",
      "title": "Jazz",
      "titleEn": "Jazz",
      "artist": "Gaho",
      "releaseDate": "2023-09-16",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 88
    },
    {
      "id": "55",
      "title": "Blues",
      "titleEn": "Blues",
      "artist": "Gaho",
      "releaseDate": "2022-06-29",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 47
    },
    {
      "id": "56",
      "title": "Soul",
      "titleEn": "Soul",
      "artist": "Gaho",
      "releaseDate": "2021-03-24",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 46
    },
    {
      "id": "57",
      "title": "Funk",
      "titleEn": "Funk",
      "artist": "Gaho",
      "releaseDate": "2020-02-18",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 45
    },
    {
      "id": "58",
      "title": "Rock",
      "titleEn": "Rock",
      "artist": "Gaho",
      "releaseDate": "2019-07-26",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 44
    },
    {
      "id": "59",
      "title": "Pop",
      "titleEn": "Pop",
      "artist": "Gaho",
      "releaseDate": "2023-10-03",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 87
    },
    {
      "id": "60",
      "title": "Ballad",
      "titleEn": "Ballad",
      "artist": "Gaho",
      "releaseDate": "2022-01-20",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 43
    },
    {
      "id": "61",
      "title": "Acoustic",
      "titleEn": "Acoustic",
      "artist": "Gaho",
      "releaseDate": "2021-02-11",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 42
    },
    {
      "id": "62",
      "title": "Electric",
      "titleEn": "Electric",
      "artist": "Gaho",
      "releaseDate": "2020-10-15",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 41
    },
    {
      "id": "63",
      "title": "Digital",
      "titleEn": "Digital",
      "artist": "Gaho",
      "releaseDate": "2019-05-08",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 40
    },
    {
      "id": "64",
      "title": "Analog",
      "titleEn": "Analog",
      "artist": "Gaho",
      "releaseDate": "2023-11-27",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 86
    },
    {
      "id": "65",
      "title": "Vintage",
      "titleEn": "Vintage",
      "artist": "Gaho",
      "releaseDate": "2022-03-30",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 39
    },
    {
      "id": "66",
      "title": "Modern",
      "titleEn": "Modern",
      "artist": "Gaho",
      "releaseDate": "2021-06-18",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 38
    },
    {
      "id": "67",
      "title": "Classic",
      "titleEn": "Classic",
      "artist": "Gaho",
      "releaseDate": "2020-09-22",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 37
    },
    {
      "id": "68",
      "title": "Contemporary",
      "titleEn": "Contemporary",
      "artist": "Gaho",
      "releaseDate": "2019-12-05",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 36
    },
    {
      "id": "69",
      "title": "Future",
      "titleEn": "Future",
      "artist": "Gaho",
      "releaseDate": "2023-12-14",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 85
    },
    {
      "id": "70",
      "title": "Past",
      "titleEn": "Past",
      "artist": "Gaho",
      "releaseDate": "2022-02-16",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 35
    },
    {
      "id": "71",
      "title": "Present",
      "titleEn": "Present",
      "artist": "Gaho",
      "releaseDate": "2021-08-09",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 34
    },
    {
      "id": "72",
      "title": "Moment",
      "titleEn": "Moment",
      "artist": "Gaho",
      "releaseDate": "2020-11-03",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 33
    },
    {
      "id": "73",
      "title": "Instant",
      "titleEn": "Instant",
      "artist": "Gaho",
      "releaseDate": "2019-03-13",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 32
    },
    {
      "id": "74",
      "title": "Eternal",
      "titleEn": "Eternal",
      "artist": "Gaho",
      "releaseDate": "2024-01-08",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 93
    },
    {
      "id": "75",
      "title": "Infinite",
      "titleEn": "Infinite",
      "artist": "Gaho",
      "releaseDate": "2022-04-25",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 31
    },
    {
      "id": "76",
      "title": "Endless",
      "titleEn": "Endless",
      "artist": "Gaho",
      "releaseDate": "2021-09-14",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 30
    },
    {
      "id": "77",
      "title": "Timeless",
      "titleEn": "Timeless",
      "artist": "Gaho",
      "releaseDate": "2020-07-28",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 29
    },
    {
      "id": "78",
      "title": "Limitless",
      "titleEn": "Limitless",
      "artist": "Gaho",
      "releaseDate": "2019-10-19",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 28
    },
    {
      "id": "79",
      "title": "Boundless",
      "titleEn": "Boundless",
      "artist": "Gaho",
      "releaseDate": "2024-02-23",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 92
    },
    {
      "id": "80",
      "title": "Fearless",
      "titleEn": "Fearless",
      "artist": "Gaho",
      "releaseDate": "2022-05-17",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 27
    },
    {
      "id": "81",
      "title": "Breathless",
      "titleEn": "Breathless",
      "artist": "Gaho",
      "releaseDate": "2021-11-30",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 26
    },
    {
      "id": "82",
      "title": "Speechless",
      "titleEn": "Speechless",
      "artist": "Gaho",
      "releaseDate": "2020-06-24",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 25
    },
    {
      "id": "83",
      "title": "Restless",
      "titleEn": "Restless",
      "artist": "Gaho",
      "releaseDate": "2019-02-05",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 24
    },
    {
      "id": "84",
      "title": "Weightless",
      "titleEn": "Weightless",
      "artist": "Gaho",
      "releaseDate": "2024-03-12",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 91
    },
    {
      "id": "85",
      "title": "Wireless",
      "titleEn": "Wireless",
      "artist": "Gaho",
      "releaseDate": "2022-07-06",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 23
    },
    {
      "id": "86",
      "title": "Seamless",
      "titleEn": "Seamless",
      "artist": "Gaho",
      "releaseDate": "2021-10-21",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 22
    },
    {
      "id": "87",
      "title": "Flawless",
      "titleEn": "Flawless",
      "artist": "Gaho",
      "releaseDate": "2020-08-14",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 21
    },
    {
      "id": "88",
      "title": "Priceless",
      "titleEn": "Priceless",
      "artist": "Gaho",
      "releaseDate": "2019-11-27",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 20
    },
    {
      "id": "89",
      "title": "Graceful",
      "titleEn": "Graceful",
      "artist": "Gaho",
      "releaseDate": "2024-04-30",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 90
    },
    {
      "id": "90",
      "title": "Powerful",
      "titleEn": "Powerful",
      "artist": "Gaho",
      "releaseDate": "2022-08-19",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 19
    },
    {
      "id": "91",
      "title": "Peaceful",
      "titleEn": "Peaceful",
      "artist": "Gaho",
      "releaseDate": "2021-12-16",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 18
    },
    {
      "id": "92",
      "title": "Wonderful",
      "titleEn": "Wonderful",
      "artist": "Gaho",
      "releaseDate": "2020-05-28",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 17
    },
    {
      "id": "93",
      "title": "Colorful",
      "titleEn": "Colorful",
      "artist": "Gaho",
      "releaseDate": "2019-09-11",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 16
    },
    {
      "id": "94",
      "title": "Meaningful",
      "titleEn": "Meaningful",
      "artist": "Gaho",
      "releaseDate": "2024-05-24",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 89
    },
    {
      "id": "95",
      "title": "Grateful",
      "titleEn": "Grateful",
      "artist": "Gaho",
      "releaseDate": "2022-09-23",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 15
    },
    {
      "id": "96",
      "title": "Joyful",
      "titleEn": "Joyful",
      "artist": "Gaho",
      "releaseDate": "2021-01-07",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 14
    },
    {
      "id": "97",
      "title": "Delightful",
      "titleEn": "Delightful",
      "artist": "Gaho",
      "releaseDate": "2020-03-19",
      "type": "single",
      "coverImage": "images/releases/album-cover_running.jpeg",
      "featured": false,
      "popularity": 13
    },
    {
      "id": "98",
      "title": "Cheerful",
      "titleEn": "Cheerful",
      "artist": "Gaho",
      "releaseDate": "2019-06-04",
      "type": "single",
      "coverImage": "images/releases/album-cover_start.jpg",
      "featured": false,
      "popularity": 12
    },
    {
      "id": "99",
      "title": "Playful",
      "titleEn": "Playful",
      "artist": "Gaho",
      "releaseDate": "2024-06-11",
      "type": "single",
      "coverImage": "images/releases/album-cover_yellow-light.jpg",
      "featured": false,
      "popularity": 88
    }
  ]
};

